pytan.exceptions module
=======================

.. automodule:: pytan.exceptions
    :show-inheritance:


Exception Classes
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Exceptions used throughout :mod:`pytan`:

.. autoexception:: pytan.exceptions.HandlerError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.HumanParserError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.DefinitionParserError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.RunFalse
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.PytanHelp
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.PollingError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.TimeoutException
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.HttpError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.AuthorizationError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.BadResponseError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.NotFoundError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.VersionMismatchError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:


.. autoexception:: pytan.exceptions.RunPluginError
    :members:
    :show-inheritance:
    :undoc-members:
    :private-members:
